const express = require('express')
const bodyParser = require('body-parser')
const passport = require('passport')
const itemRoutes = require('./src/routes/admin')
const shopRoutes = require('./src/routes/shop')
const userRoutes = require('./src/routes/user/')
require('./src/configuration/database')
const app = express()
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended: false}))
app.use(passport.initialize())
app.use(express.static('uploads'))
app.use('/item', itemRoutes)
app.use('/shop', shopRoutes)
app.use('/user', userRoutes)

app.listen(3000, ()=>console.log('server is running'))